// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2c2d725a-2dad-4a0a-b685-455fb63627c0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_bCzGP1S7W",
    "aws_user_pools_web_client_id": "4mt81k2pq78h4ov4hobkdu7sae",
    "oauth": {}
};


export default awsmobile;
